### ISSUE TITLE
Write void function with reference parameter of type tourType

### ISSUE THREAD

**Issue by codesidian** [codesidian/SDI#6]
Write the definition of a void function with reference parameter of type tourType to input
in a variable of type tourType.

**Comment by codesidian** [comment]
I have written a void function with the reference parameter which is of the type tourType. It will take input to change the data stored in the distance variable of type tourType.
```
void changeDistance(tourType &dist) {
	
	cout << "\nPlease enter the distance...\n";
	cin >> dist.distance;

}
```

**Comment by petrindade** [comment]
Well done!
